### ISSUE TITLE
Rare issue where grad_minui messes with ACE3's initialization

### ISSUE THREAD

**Issue by LarsAsprah** [DerZade/grad_minui#7]
Yo. I know this is far from a ready product, but I just thought to come by and report a peculiar bug I've encountered while playing with this on. 

With specific scenarios, it interferes with ace's init and features like medical, interaction and such fail to load. Took me a while to pin it down but I'm now positive that this mod is the culprit.

The ff. scenarios are where this issue was encountered. Doesn't seem to be a particular correlation between them from a cursory look through the editor and the mission files, aside from the aforementioned bug.

https://steamcommunity.com/sharedfiles/filedetails/?id=197405934
https://steamcommunity.com/sharedfiles/filedetails/?id=193996842
https://steamcommunity.com/sharedfiles/filedetails/?id=1480331340

For now I'll drop this from my modlist, but I do look forward to the finished version!

**Comment by DerZade** [comment]
Hey,
Thanks a lot for bug report. Just to make sure, that I understood correctly:
Sometimes the `grad_minui` blocks the whole ACE init and therefore none of the ACE features are working. 

Correct?

**Comment by LarsAsprah** [comment]
Yes. Only with those specific usermade scenarios however, which is puzzling since in most others I didn't encounter any problems.

**Comment by DerZade** [comment]
Okaayy 🤔 
We are playing with this mod and ace for a couple months now with absolutely no problems so that is weird and I can't think of anything that could cause such a behavior.
Are you 100% sure that this is an issue with `grad_minui`? If yes, what makes you so sure? 
Which mods were you using and can I look at your RPT?

**Comment by LarsAsprah** [comment]
Absolutely positive.
By tedious process of elimination.
Believe me, this mod was literally the last thing I suspected when I first encountered this issue, and the last thing I ticked off when I was trying to pin down the culprit.

Here's the RPT from a test session of me launching Arma 3, playing through Brief Lives - Episode 3.5 a bit and exiting. As expected, ace failed to load properly. Only mods loaded were CBA, ace and grad_miniui

https://mega.nz/#!Fl90XYZJ!vEfyJKvUbnBwvNP0X3o1THXnUboYwn4u8EkqH4maJDY

**Comment by LarsAsprah** [comment]
For comparison here's the RPT from an almost identical session but without grad_miniui loaded.
ace working as intended. 

https://mega.nz/#!k980DACD!Vx5WdOwRTRyCFbFe0wVbiLWMUcNqINRsqWY8-Y41t2c

**Comment by SlantX** [comment]
Could you please provide the scenario that you used to test this with only CBA, ACE and grad_minui so we can take a look at this? I am unsure which of the previously linked missions you mean.

**Comment by DerZade** [comment]
Looks like the script error already mentioned in #4 causes a problem. I fixed that error a couple months ago, but haven't release it on GitHub because I didn't think somebody outside our group actually uses this mod 😅 
I'll make a new release in a couple of minutes.

PS: 
BTW it makes absolutely no sense that a script error in my mod causes ACE to not load, but I hope this fixes it. 

![](https://i.imgur.com/9EBzNoH.png)

**Comment by DerZade** [comment]
Here is the newest release: @LarsAsprah please check whether the issue is resolved.
https://github.com/DerZade/grad_minui/releases/tag/0.5.0

**Comment by LarsAsprah** [comment]
Just got around to being able to test the new release.
Can confirm that the issue has been resolved.

**Comment by DerZade** [comment]
Nice. I am glad it was such a easy fix 😅
